version: '2'
services:
  
    web:
        restart: always
        build: ./web
        ports:
            - "80:8000"
        volumes:
            - db-data:/data/db

    static:
        restart: always
        build: ./static
        ports:
            - "8000:8000"

volumes:
  db-data: