swagger: '2.0'

# This is the document metadata
info:
  version: "0.0.2"
  title: Crocodile Beak Hackathon

# Paths
paths:
  /product/{rfid}:
      get:
        operationId: "endpoints.get_rfid"
        parameters:
          - in: path
            required: true
            name: rfid
            type: "string"
        responses:
          200:
            description: "Returns 'true' if product does not violate any filters"
          404:
            description: "Product is not known."

  /product/:
    post:
      operationId: "endpoints.post_product"
      parameters:
      - in: body
        required: true
        name: product
        schema:
              $ref: "#/definitions/Product"
      responses:
        200:
          description: "Successfully saved RFID tag and bar code."
  
  /preferences/:
    post:
      operationId: "endpoints.post_preference"
      parameters:
      - in: body
        required: true
        name: preferences
        schema:
          type: "array"
          items:
            $ref: "#/definitions/Preference"
      responses:
        200:
          description: "Successfully saved RFID tag and bar code."
  
definitions:
  Product:
    type: "object"
    properties:
      rfid:
        type: "string"
        description: "The RFID tag of the price tag matching the product."
      barcode:
        type: "string"
        description: "The bar code the product."
  
  Preference:
    type: "object"
    properties:
      name:
        type: "string"
        description: "The name of the ingredient."
      selected:
        type: "boolean"
        description: "'true' if selected for warning, 'fakse' if allowed."
